name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: List files (debug)
      run: |
        pwd
        ls -la
        ls -la CalculatorApp/

    - name: Restore dependencies
      run: dotnet restore CalculatorApp/CalculatorApp.csproj

    - name: Build
      run: dotnet build CalculatorApp/CalculatorApp.csproj --no-restore

    - name: Test
      run: dotnet test CalculatorApp/CalculatorApp.Tests.csproj
